name: Categorize Tracker
description: File a report to identify a tracker
title: "[Unidentified Tracker]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help catalog TrackerDB!
  - type: markdown
    attributes:
      value: |
        ## Metadata
  - type: input
    id: request
    attributes:
      label: Request
      description: What is the URL of the uncategorized tracker?
      placeholder: analytics.google.com
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: On what site is the tracker located? Where did it appear?
      placeholder: https://www.cnn.com/
    validations:
      required: true
  - type: input
    id: tracker-company
    attributes:
      label: Tracker Company
      description: What company owns the tracker?
      placeholder: Google
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Tracker Information
  - type: input
    id: company-website
    attributes:
      label: Company Website
      description: What is the website URL?
      placeholder: https://www.google.com/
    validations:
      required: false
  - type: input
    id: company-privacy-policy
    attributes:
      label: Privacy Policy
      description: Provide a link to the company's privacy policy. (Usually, a link located at the bottom of their website.)
      placeholder: https://policies.google.com/privacy
    validations:
      required: false
  - type: textarea
    id: company-description
    attributes:
      label: Describe the company
      description: Tell us what you know about the company. Ensure descriptions are informative and impartial. Please fact check the information if using generative AI. Be prepared to cite sources, if necessary.
    validations:
      required: false
 
  - type: dropdown
    id: tracker-category
    attributes:
      label: Category
      description: Which category does this request **BEST** belong to? You can find category descriptions [here](https://github.com/ghostery/trackerdb/blob/main/docs/categories.md).
      options:
        - Adult Advertising
        - Advertising
        - Audio/Video Player
        - CDN
        - Comments
        - Consent Management
        - Customer Interaction
        - Email
        - Essential
        - Extensions
        - Hosting
        - Miscellaneous
        - Site Analytics
        - Social Media
        - Telemetry
    validations:
      required: false
  - type: dropdown
    id: tracker-request-type
    attributes:
      label: Request Type
      description: What kind web request is the tracker?
      options:
        - beacon
        - csp_report
        - font
        - image
        - imageset
        - main_frame
        - media
        - object
        - object_subrequest
        - ping
        - script
        - speculative
        - stylesheet
        - sub_frame
        - websocket
        - web_manifest
        - xmlhttprequest
        - xml_dtd
        - xslt
        - other
    validations:
      required: false
  - type: textarea
    id: tracker-additional-information
    attributes:
      label: Additional Information
      description: Do you have any additional information to include (e.g., any other websites where this tracker appears)?
    validations:
      required: false
  - type: textarea
    id: tracker-filters
    attributes:
      label: Filters
      description: Can you suggest any filters to block the request? This will be automatically formatted into code, so no need for backticks.
      render: shell
      placeholder: "||analytics.google.com^$third-party"
    validations:
      required: false
